# Generated by Django 3.2.5 on 2021-07-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0004_auto_20210710_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
