# Generated by Django 3.2.5 on 2021-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0005_remove_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Office', 'Office')], max_length=255, null=True),
        ),
    ]
