# Generated by Django 3.2.5 on 2021-07-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Menu',
            field=models.ManyToManyField(blank=True, to='restaurantApp.Menu'),
        ),
    ]
