# Generated by Django 3.2.5 on 2021-07-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0003_order_shipping_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on_create', 'on-create'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Preparing', 'Preparing'), ('Delivered', 'Delivered')], default='on_crate', max_length=20),
        ),
    ]
