# Generated by Django 3.2.5 on 2021-07-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on_create', 'on_create'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Preparing', 'Preparing'), ('Delivered', 'Delivered')], default='on_create', max_length=20),
        ),
    ]
