# Generated by Django 3.2.5 on 2021-07-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Preparing', 'Preparing'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
